# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    # avoid_relative_lib_imports: false
    unawaited_futures: false

    # checking off in the debug phase

analyzer:
  exclude:
  errors:
    todo: ignore
    unused_field: ignore 