name: sticky_cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: microtears <microtears@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  args: ^1.5.2
  intl: ^0.15.8

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
